POST http://localhost:8080/students

###
POST http://localhost:8080/students/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="students.csv"
Content-Type: text/csv

< F:\Downloads\students.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--